import React, { useState, useMemo } from 'react';
import {
  PieChart, Pie, Cell, Tooltip, Legend
} from 'recharts';
import {
  AlertTriangle, Copy, Activity, CheckCircle2,
  Search, Sparkles, ListTodo, Layers, Fingerprint,
  X, ArrowRightLeft, Check, AlertCircle, Info, Eye
} from 'lucide-react';
import { Link } from 'react-router-dom';
import { useDataset } from '../contexts/DatasetContext';
import { runDetectionEngine } from '../utils/detectionEngine.js';

export default function Duplicates() {
  const { dataset, setDetectionResults } = useDataset();
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [analysisComplete, setAnalysisComplete] = useState(false);
  const [activeTab, setActiveTab] = useState('duplicates');
  const [selectedRowForModal, setSelectedRowForModal] = useState(null);

  const [chartData, setChartData] = useState([]);
  const [recommendations, setRecommendations] = useState([]);
  const [duplicateRows, setDuplicateRows] = useState([]);
  const [anomalyRows, setAnomalyRows] = useState([]);
  const [stats, setStats] = useState({
    totalIssues: 0,
    duplicates: 0,
    anomalies: 0,
    cleanPercent: '100%'
  });

    const handleRunAnalysis = () => {
    if (!dataset || !dataset.rows || !dataset.headers) {
      alert('Please upload a dataset first.');
      return;
    }

    setIsAnalyzing(true);

    try {
      const rows = dataset.rows;
      const headers = dataset.headers;

      // Run the complete Phase-B detection engine.
      const results = runDetectionEngine(rows, headers);
      setDetectionResults(results);

      const {
        duplicate_results,
        anomaly_results,
        rule_violation_results,
        fuzzy_duplicate_results,
        inconsistency_results,
        detection_summary
      } = results;

      /*
       * Convert detection evidence into rows that the
       * existing preview table can display with full comparison context.
       */
      const duplicatePreview = [
        ...duplicate_results,
        ...fuzzy_duplicate_results
      ]
        .slice(0, 50)
        .map((item) => {
          const targetIndex = item.duplicateOf !== undefined ? item.duplicateOf : item.similarTo;
          const targetRow = targetIndex !== undefined && rows[targetIndex] ? rows[targetIndex] : null;
          return {
            ...rows[item.row],
            id: item.row,
            _issue: item.issueType,
            _method: item.detectionMethod,
            _severity: item.severity,
            _confidence: item.confidence,
            _reason: item.reason,
            _recommendedAction: item.recommendedAction,
            _targetIndex: targetIndex,
            _targetRow: targetRow,
            _similarity: item.similarity
          };
        });

      // Group anomaly evidence by dataset row so the same row
      // is shown only once even when multiple detectors flag it.
      const anomalyMap = new Map();

      anomaly_results.forEach((item) => {
        if (!anomalyMap.has(item.row)) {
          anomalyMap.set(item.row, {
            ...rows[item.row],
            id: item.row,
            _issue: item.issueType,
            _methods: [],
            _headers: [],
            _details: [],
            _severity: item.severity,
            _confidence: item.confidence
          });
        }

        const existing = anomalyMap.get(item.row);

        if (item.detectionMethod && !existing._methods.includes(item.detectionMethod)) {
          existing._methods.push(item.detectionMethod);
        }

        if (item.column && !existing._headers.includes(item.column)) {
          existing._headers.push(item.column);
        }

        existing._details.push({
          column: item.column,
          issueType: item.issueType,
          method: item.detectionMethod,
          reason: item.reason,
          recommendedAction: item.recommendedAction,
          severity: item.severity,
          confidence: item.confidence,
          value: item.originalValue ?? item.value
        });

        // Keep the highest severity/confidence evidence available.
        if (item.severity === 'High') {
          existing._severity = 'High';
        }

        if (
          typeof item.confidence === 'number' &&
          (
            typeof existing._confidence !== 'number' ||
            item.confidence > existing._confidence
          )
        ) {
          existing._confidence = item.confidence;
        }
      });

      const anomalyPreview = Array.from(anomalyMap.values()).slice(0, 50);

      setDuplicateRows(duplicatePreview);
      setAnomalyRows(anomalyPreview);

      /*
       * Use the summary generated by the detection engine.
       */
      const totalIssues = detection_summary.totalIssues;

      const duplicateCount =
        detection_summary.exactDuplicates +
        detection_summary.fuzzyDuplicates;

      const anomalyCount =
        detection_summary.statisticalAnomalies +
        detection_summary.isolationForestAnomalies;

      const cleanPercent = Math.max(
        0,
        100 - (totalIssues / rows.length) * 100
      ).toFixed(1);

      setStats({
        totalIssues,
        duplicates: duplicateCount,
        anomalies: anomalyCount,
        cleanPercent: `${cleanPercent}%`
      });

      /*
       * Quality breakdown chart.
       */
      const pieData = [
        {
          name: 'Clean Data',
          value: parseFloat(cleanPercent),
          color: '#10b981'
        },
        {
          name: 'Duplicates',
          value: parseFloat(
            ((duplicateCount / rows.length) * 100).toFixed(1)
          ),
          color: '#f59e0b'
        },
        {
          name: 'Anomalies',
          value: parseFloat(
            ((anomalyCount / rows.length) * 100).toFixed(1)
          ),
          color: '#ef4444'
        }
      ];

      setChartData(pieData);

      /*
       * Explainable recommendations.
       *
       * Detection only — no data is modified or deleted here.
       */
      const recs = [];

      if (duplicate_results.length > 0) {
        recs.push({
          issue: 'Exact Duplicates',
          rec: 'Review',
          reason: `Found ${duplicate_results.length} exact duplicate records. Review them before any removal is approved.`
        });
      }

      if (fuzzy_duplicate_results.length > 0) {
        recs.push({
          issue: 'Fuzzy Duplicates',
          rec: 'Review',
          reason: `Found ${fuzzy_duplicate_results.length} records with high similarity. Review the suggested matches before making changes.`
        });
      }

      if (anomaly_results.length > 0) {
        const topAnomaly = anomaly_results[0];

        recs.push({
          issue: 'Anomalies',
          rec: 'Investigate',
          reason: `${anomaly_results.length} statistical or multivariate anomalies were detected. Example: ${topAnomaly.column}.`
        });
      }

      if (rule_violation_results.length > 0) {
        recs.push({
          issue: 'Rule Violations',
          rec: 'Review',
          reason: `Found ${rule_violation_results.length} values or cross-column relationships that violate defined validation rules.`
        });
      }

      if (inconsistency_results.length > 0) {
        recs.push({
          issue: 'Category Inconsistencies',
          rec: 'Review',
          reason: `Found ${inconsistency_results.length} possible category/typing inconsistencies. Suggested corrections require user approval.`
        });
      }

      if (recs.length === 0) {
        recs.push({
          issue: 'All Clear',
          rec: 'No Action',
          reason: 'No duplicate, anomaly, rule violation, or inconsistency was detected.'
        });
      }

      setRecommendations(recs);

      setIsAnalyzing(false);
      setAnalysisComplete(true);
    } catch (error) {
      console.error('Detection engine failed:', error);
      console.error('Error message:', error?.message);
      console.error('Error stack:', error?.stack);

      setIsAnalyzing(false);

      alert(
        `Detection engine error: ${error?.message || 'Unknown error'}`
      );
    }
  };

  return (
    <div className="animate-fade-in max-w-7xl mx-auto text-slate-800 dark:text-white transition-colors duration-500">
      <div className="mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-3xl font-bold tracking-wide text-slate-900 dark:text-white transition-colors">Data Quality Scan</h2>
          <p className="text-slate-500 dark:text-[#8ba3c9] mt-2 font-light transition-colors">
            Detect exact duplicates, fuzzy matches, and structural anomalies.
          </p>
        </div>
        {analysisComplete && (
          <button
            onClick={() => setAnalysisComplete(false)}
            className="px-4 py-2 bg-slate-100 hover:bg-slate-200 dark:bg-[#0a1f44] dark:hover:bg-[#112a58] text-slate-700 dark:text-[#8ba3c9] rounded-lg transition-colors text-sm font-medium border border-slate-200 dark:border-[#1a325a]"
          >
            Reset Scan
          </button>
        )}
      </div>

      {!analysisComplete && !isAnalyzing && (
        <div className="bg-white dark:bg-[#05142e]/80 backdrop-blur-sm p-12 rounded-2xl shadow-md dark:shadow-lg border border-slate-200 dark:border-[#1a325a] min-h-[400px] flex flex-col items-center justify-center text-center transition-colors duration-500">
          {!dataset ? (
            <>
              <div className="w-20 h-20 bg-rose-50 dark:bg-rose-500/10 rounded-full flex items-center justify-center mb-6 border border-rose-100 dark:border-rose-500/20">
                <AlertTriangle className="w-10 h-10 text-rose-500 dark:text-rose-400" />
              </div>
              <h3 className="text-2xl font-semibold mb-3 text-slate-800 dark:text-white">No Dataset Detected</h3>
              <p className="text-slate-500 dark:text-[#8ba3c9] max-w-md mb-8">
                You need to upload a CSV dataset before you can run a quality scan.
              </p>
              <Link
                to="/upload"
                className="px-8 py-3.5 bg-blue-600 hover:bg-blue-500 text-white rounded-xl shadow-lg font-medium tracking-wide flex items-center gap-3 transition-all hover:scale-[1.02] active:scale-[0.98]"
              >
                Go to Upload
              </Link>
            </>
          ) : (
            <>
              <div className="w-20 h-20 bg-indigo-50 dark:bg-indigo-500/10 rounded-full flex items-center justify-center mb-6 border border-indigo-100 dark:border-indigo-500/20">
                <Layers className="w-10 h-10 text-indigo-500 dark:text-indigo-400" />
              </div>
              <h3 className="text-2xl font-semibold mb-3 text-slate-800 dark:text-white">Ready for Quality Scan</h3>
              <p className="text-slate-500 dark:text-[#8ba3c9] max-w-md mb-8">
                Click the button below to scan your dataset for duplicates, fuzzy similarities, and statistical outliers across all columns.
              </p>
              <button
                onClick={handleRunAnalysis}
                className="px-8 py-3.5 bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white rounded-xl shadow-lg shadow-indigo-500/25 font-medium tracking-wide flex items-center gap-3 transition-all hover:scale-[1.02] active:scale-[0.98]"
              >
                <Search className="w-5 h-5" />
                Run Quality Scan
              </button>
            </>
          )}
        </div>
      )}

      {isAnalyzing && (
        <div className="bg-white dark:bg-[#05142e]/80 backdrop-blur-sm p-12 rounded-2xl shadow-md dark:shadow-lg border border-slate-200 dark:border-[#1a325a] min-h-[400px] flex flex-col items-center justify-center text-center transition-colors duration-500">
          <div className="relative w-24 h-24 mb-8">
            <div className="absolute inset-0 border-4 border-slate-100 dark:border-[#0a1f44] rounded-full"></div>
            <div className="absolute inset-0 border-4 border-indigo-500 rounded-full border-t-transparent animate-spin"></div>
            <div className="absolute inset-0 flex items-center justify-center">
              <Sparkles className="w-8 h-8 text-indigo-500 animate-pulse" />
            </div>
          </div>
          <h3 className="text-xl font-medium text-slate-800 dark:text-white mb-2 animate-pulse">Running Deep Scan...</h3>
          <p className="text-slate-500 dark:text-[#8ba3c9]">Calculating TF-IDF matrices, hashing rows, and finding Isolation Forests.</p>
        </div>
      )}

      {analysisComplete && (
        <div className="space-y-6 animate-fade-in">
          {/* Top Stats Row */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            <div className="bg-white dark:bg-[#05142e]/80 backdrop-blur-sm p-6 rounded-2xl border border-slate-200 dark:border-[#1a325a] shadow-sm relative overflow-hidden group">
              <div className="absolute -right-4 -top-4 w-24 h-24 bg-rose-500/5 dark:bg-rose-400/5 rounded-full group-hover:scale-150 transition-transform duration-500"></div>
              <div className="flex justify-between items-start mb-4 relative z-10">
                <div>
                  <p className="text-sm font-medium text-slate-500 dark:text-[#8ba3c9]">Total Issues</p>
                  <h3 className="text-3xl font-bold text-slate-800 dark:text-white mt-1">{stats.totalIssues}</h3>
                </div>
                <div className="p-2 bg-rose-50 dark:bg-rose-500/10 rounded-lg">
                  <AlertTriangle className="w-5 h-5 text-rose-500 dark:text-rose-400" />
                </div>
              </div>
              <p className="text-xs text-slate-500 dark:text-[#8ba3c9] relative z-10">Rows needing attention</p>
            </div>

            <div className="bg-white dark:bg-[#05142e]/80 backdrop-blur-sm p-6 rounded-2xl border border-slate-200 dark:border-[#1a325a] shadow-sm relative overflow-hidden group">
              <div className="absolute -right-4 -top-4 w-24 h-24 bg-amber-500/5 dark:bg-amber-400/5 rounded-full group-hover:scale-150 transition-transform duration-500"></div>
              <div className="flex justify-between items-start mb-4 relative z-10">
                <div>
                  <p className="text-sm font-medium text-slate-500 dark:text-[#8ba3c9]">Duplicates</p>
                  <h3 className="text-3xl font-bold text-slate-800 dark:text-white mt-1">{stats.duplicates}</h3>
                </div>
                <div className="p-2 bg-amber-50 dark:bg-amber-500/10 rounded-lg">
                  <Copy className="w-5 h-5 text-amber-500 dark:text-amber-400" />
                </div>
              </div>
              <p className="text-xs text-slate-500 dark:text-[#8ba3c9] relative z-10">Exact & Fuzzy matches</p>
            </div>

            <div className="bg-white dark:bg-[#05142e]/80 backdrop-blur-sm p-6 rounded-2xl border border-slate-200 dark:border-[#1a325a] shadow-sm relative overflow-hidden group">
              <div className="absolute -right-4 -top-4 w-24 h-24 bg-purple-500/5 dark:bg-purple-400/5 rounded-full group-hover:scale-150 transition-transform duration-500"></div>
              <div className="flex justify-between items-start mb-4 relative z-10">
                <div>
                  <p className="text-sm font-medium text-slate-500 dark:text-[#8ba3c9]">Anomalies</p>
                  <h3 className="text-3xl font-bold text-slate-800 dark:text-white mt-1">{stats.anomalies}</h3>
                </div>
                <div className="p-2 bg-purple-50 dark:bg-purple-500/10 rounded-lg">
                  <Activity className="w-5 h-5 text-purple-500 dark:text-purple-400" />
                </div>
              </div>
              <p className="text-xs text-slate-500 dark:text-[#8ba3c9] relative z-10">Statistical outliers found</p>
            </div>

            <div className="bg-white dark:bg-[#05142e]/80 backdrop-blur-sm p-6 rounded-2xl border border-slate-200 dark:border-[#1a325a] shadow-sm relative overflow-hidden group">
              <div className="absolute -right-4 -top-4 w-24 h-24 bg-emerald-500/5 dark:bg-emerald-400/5 rounded-full group-hover:scale-150 transition-transform duration-500"></div>
              <div className="flex justify-between items-start mb-4 relative z-10">
                <div>
                  <p className="text-sm font-medium text-slate-500 dark:text-[#8ba3c9]">Clean Data</p>
                  <h3 className="text-2xl font-bold text-slate-800 dark:text-white mt-2">{stats.cleanPercent}</h3>
                </div>
                <div className="p-2 bg-emerald-50 dark:bg-emerald-500/10 rounded-lg">
                  <CheckCircle2 className="w-5 h-5 text-emerald-500 dark:text-emerald-400" />
                </div>
              </div>
              <p className="text-xs text-slate-500 dark:text-[#8ba3c9] relative z-10">Dataset overall health</p>
            </div>
          </div>

          {/* Main Content Grid */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

            {/* Chart Area */}
            <div className="lg:col-span-2 bg-white dark:bg-[#05142e]/80 backdrop-blur-sm p-6 rounded-2xl border border-slate-200 dark:border-[#1a325a] shadow-sm">
              <div className="flex items-center justify-between mb-2">
                <h3 className="text-lg font-semibold text-slate-800 dark:text-white flex items-center gap-2">
                  <AlertTriangle className="w-5 h-5 text-rose-500" />
                  Data Quality Breakdown
                </h3>
              </div>
              <div className="h-[320px] w-full flex items-center justify-center">
                <PieChart width={500} height={320}>
                  <Pie
                    data={chartData}
                    cx="50%"
                    cy="50%"
                    innerRadius={80}
                    outerRadius={110}
                    paddingAngle={5}
                    dataKey="value"
                    stroke="none"
                  >
                    {chartData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>

                  <Tooltip
                    contentStyle={{
                      backgroundColor: 'rgba(15, 23, 42, 0.9)',
                      borderColor: '#1e293b',
                      color: '#f8fafc',
                      borderRadius: '8px',
                      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)'
                    }}
                    itemStyle={{ color: '#f8fafc' }}
                    formatter={(value) => `${value}%`}
                  />

                  <Legend
                    verticalAlign="bottom"
                    height={36}
                    iconType="circle"
                    wrapperStyle={{
                      fontSize: '14px',
                      paddingTop: '20px'
                    }}
                  />
                </PieChart>
              </div>
            </div>

            {/* Recommendations & Models */}
            <div className="space-y-6">
              <div className="bg-white dark:bg-[#05142e]/80 backdrop-blur-sm p-6 rounded-2xl border border-slate-200 dark:border-[#1a325a] shadow-sm">
                <h3 className="text-lg font-semibold text-slate-800 dark:text-white mb-4 flex items-center gap-2">
                  <ListTodo className="w-5 h-5 text-indigo-500" />
                  AI Recommendations
                </h3>
                <div className="space-y-4">
                  {recommendations.map((item, i) => (
                    <div key={i} className="p-3 bg-slate-50 dark:bg-[#0a1f44] rounded-xl border border-slate-100 dark:border-[#1a325a]">
                      <div className="flex items-center justify-between mb-1">
                        <span className="font-medium text-sm text-slate-800 dark:text-white">{item.issue}</span>
                        <span className="text-[10px] font-bold px-2 py-0.5 bg-indigo-100 text-indigo-700 dark:bg-indigo-500/20 dark:text-indigo-300 rounded-full">
                          {item.rec}
                        </span>
                      </div>
                      <p className="text-xs text-slate-500 dark:text-[#8ba3c9] leading-relaxed">
                        {item.reason}
                      </p>
                    </div>
                  ))}
                </div>
              </div>

              <div className="bg-gradient-to-br from-purple-600 to-rose-600 rounded-2xl p-6 text-white shadow-md relative overflow-hidden group">
                <div className="absolute right-0 top-0 w-32 h-32 bg-white/10 rounded-full -translate-y-16 translate-x-12 group-hover:scale-110 transition-transform duration-700"></div>
                <h3 className="text-lg font-semibold mb-4 relative z-10 flex items-center gap-2">
                  <Activity className="w-5 h-5" />
                  Detection Models Used
                </h3>
                <ul className="space-y-3 relative z-10">
                  <li className="flex items-center gap-3 text-sm">
                    <div className="w-2 h-2 rounded-full bg-white/80"></div>
                    Isolation Forest (Multivariate)
                  </li>

                  <li className="flex items-center gap-3 text-sm">
                    <div className="w-2 h-2 rounded-full bg-white/80"></div>
                    Levenshtein Similarity (Fuzzy Matching)
                  </li>

                  <li className="flex items-center gap-3 text-sm">
                    <div className="w-2 h-2 rounded-full bg-white/80"></div>
                    Z-Score & IQR (Statistical)
                  </li>

                  <li className="flex items-center gap-3 text-sm">
                    <div className="w-2 h-2 rounded-full bg-white/80"></div>
                    Exact Duplicate Detection
                  </li>

                  <li className="flex items-center gap-3 text-sm">
                    <div className="w-2 h-2 rounded-full bg-white/80"></div>
                    Business Rule Validation
                  </li>

                  <li className="flex items-center gap-3 text-sm">
                    <div className="w-2 h-2 rounded-full bg-white/80"></div>
                    Cross-Column Validation
                  </li>

                  <li className="flex items-center gap-3 text-sm">
                    <div className="w-2 h-2 rounded-full bg-white/80"></div>
                    Category Inconsistency Detection
                  </li>
                </ul>
              </div>
            </div>

          </div>

          {/* Preview Table */}
          <div className="bg-white dark:bg-[#05142e]/80 backdrop-blur-sm p-6 rounded-2xl border border-slate-200 dark:border-[#1a325a] shadow-sm">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between mb-6 gap-4">
              <div>
                <h3 className="text-lg font-semibold text-slate-800 dark:text-white flex items-center gap-2">
                  <Search className="w-5 h-5 text-indigo-500" />
                  Issue Preview Viewer
                </h3>
                <p className="text-xs text-slate-400 mt-1">
                  Click on any row to open the complete side-by-side attribute comparison.
                </p>
              </div>

              <div className="flex bg-slate-100 dark:bg-[#0a1f44] p-1 rounded-lg border border-slate-200 dark:border-[#1a325a]">
                <button
                  onClick={() => { setActiveTab('duplicates'); setSelectedRowForModal(null); }}
                  className={`px-4 py-1.5 text-sm font-medium rounded-md transition-colors ${activeTab === 'duplicates' ? 'bg-white dark:bg-[#1a325a] text-indigo-600 dark:text-indigo-400 shadow-sm' : 'text-slate-500 dark:text-[#8ba3c9] hover:text-slate-700 dark:hover:text-white'}`}
                >
                  Duplicates ({duplicateRows.length})
                </button>
                <button
                  onClick={() => { setActiveTab('anomalies'); setSelectedRowForModal(null); }}
                  className={`px-4 py-1.5 text-sm font-medium rounded-md transition-colors ${activeTab === 'anomalies' ? 'bg-white dark:bg-[#1a325a] text-rose-600 dark:text-rose-400 shadow-sm' : 'text-slate-500 dark:text-[#8ba3c9] hover:text-slate-700 dark:hover:text-white'}`}
                >
                  Anomalies ({anomalyRows.length})
                </button>
              </div>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left text-sm text-slate-500 dark:text-[#8ba3c9]">
                <thead className="text-xs text-slate-700 uppercase bg-slate-50 dark:bg-[#0a1f44] dark:text-slate-300">
                  <tr>
                    <th className="px-4 py-3 rounded-l-lg">Row ID</th>
                    {dataset?.headers?.filter(h => h !== '__row_id').slice(0, 4).map((h, i) => (
                      <th key={i} className="px-4 py-3">{h}</th>
                    ))}
                    <th className="px-4 py-3">Detection Flag</th>
                    <th className="px-4 py-3 rounded-r-lg text-right">Action</th>
                  </tr>
                </thead>
                <tbody>
                  {(activeTab === 'duplicates' ? duplicateRows : anomalyRows).length > 0 ? (activeTab === 'duplicates' ? duplicateRows : anomalyRows).map((row, idx) => (
                    <tr 
                      key={idx} 
                      onClick={() => setSelectedRowForModal(row)}
                      className="border-b border-slate-100 dark:border-[#1a325a] hover:bg-indigo-50/60 dark:hover:bg-[#0a1f44] cursor-pointer transition-colors group"
                      title="Click to view full side-by-side comparison"
                    >
                      <td className="px-4 py-3 font-semibold text-slate-900 dark:text-white flex items-center gap-1.5">
                        <span className="font-mono text-indigo-600 dark:text-indigo-400 font-bold">#{row.id}</span>
                      </td>
                      {dataset?.headers?.filter(h => h !== '__row_id').slice(0, 4).map((h, i) => (
                        <td key={i} className="px-4 py-3">
                          <span className="text-slate-800 dark:text-slate-200">{String(row[h] ?? '') || <span className="text-slate-400 italic">empty</span>}</span>
                        </td>
                      ))}
                      <td className="px-4 py-3">
                        {activeTab === 'duplicates' ? (
                          <span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-semibold ${
                            row._issue === 'Exact Duplicate'
                              ? 'bg-amber-100 text-amber-800 dark:bg-amber-500/20 dark:text-amber-300 border border-amber-300 dark:border-amber-500/30'
                              : 'bg-purple-100 text-purple-800 dark:bg-purple-500/20 dark:text-purple-300 border border-purple-300 dark:border-purple-500/30'
                          }`}>
                            <Copy className="w-3 h-3" />
                            {row._issue || 'Duplicate'}
                            {row._targetIndex !== undefined && (
                              <span className="opacity-80 font-normal">➔ #{row._targetIndex}</span>
                            )}
                          </span>
                        ) : (
                          <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-rose-100 text-rose-800 dark:bg-rose-500/20 dark:text-rose-300 border border-rose-300 dark:border-rose-500/30">
                            <AlertTriangle className="w-3 h-3" />
                            {row._details?.length || 1} Outlier{(row._details?.length || 1) > 1 ? 's' : ''}
                          </span>
                        )}
                      </td>
                      <td className="px-4 py-3 text-right">
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            setSelectedRowForModal(row);
                          }}
                          className="px-3 py-1 bg-indigo-50 hover:bg-indigo-100 dark:bg-indigo-500/10 dark:hover:bg-indigo-500/20 text-indigo-600 dark:text-indigo-400 text-xs font-bold rounded-lg border border-indigo-200 dark:border-indigo-500/30 inline-flex items-center gap-1.5 transition-all group-hover:scale-105"
                        >
                          <Eye className="w-3.5 h-3.5" />
                          Compare
                        </button>
                      </td>
                    </tr>
                  )) : (
                    <tr>
                      <td colSpan={7} className="px-4 py-8 text-center text-slate-400">
                        No {activeTab} detected.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
            {activeTab === 'duplicates' && duplicateRows.length > 0 && (
              <p className="text-xs text-amber-600 dark:text-amber-400 mt-4 flex items-center gap-1.5">
                <AlertTriangle className="w-3.5 h-3.5 flex-shrink-0" />
                <span><strong>Tip:</strong> Click on any row to open the complete side-by-side comparison popup and see identical values or discrepancies.</span>
              </p>
            )}
            {activeTab === 'anomalies' && anomalyRows.length > 0 && (
              <p className="text-xs text-rose-600 dark:text-rose-400 mt-4 flex items-center gap-1.5">
                <AlertTriangle className="w-3.5 h-3.5 flex-shrink-0" />
                <span><strong>Tip:</strong> Click on any row to inspect all statistical anomalies, bounds, and rule violations flagged for that record.</span>
              </p>
            )}
          </div>

          {/* ========================================================================= */}
          {/* Dynamic Side-by-Side Comparison Modal Popup */}
          {/* ========================================================================= */}
          {selectedRowForModal && (
            <div 
              className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-slate-950/75 backdrop-blur-sm animate-fade-in"
              onClick={() => setSelectedRowForModal(null)}
            >
              <div 
                className="bg-white dark:bg-[#07193b] border border-slate-200 dark:border-[#1a3f7a] rounded-3xl shadow-2xl w-full max-w-4xl max-h-[90vh] flex flex-col overflow-hidden text-slate-800 dark:text-white transition-all transform animate-scale-in"
                onClick={(e) => e.stopPropagation()}
              >
                {/* Modal Header */}
                <div className="flex items-center justify-between p-6 border-b border-slate-100 dark:border-[#1a325a] bg-slate-50/70 dark:bg-[#05142e]/80">
                  <div className="flex items-center gap-3.5">
                    <div className="p-3 rounded-2xl bg-indigo-50 dark:bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border border-indigo-100 dark:border-indigo-500/20 shadow-sm">
                      <ArrowRightLeft className="w-6 h-6" />
                    </div>
                    <div>
                      <div className="flex items-center gap-2.5">
                        <h3 className="text-xl font-extrabold tracking-tight text-slate-900 dark:text-white">
                          {activeTab === 'duplicates'
                            ? `${selectedRowForModal._issue || 'Duplicate'} Side-by-Side Comparison`
                            : 'Anomaly Diagnostic Inspector'}
                        </h3>
                        <span className={`px-2.5 py-0.5 rounded-full text-xs font-extrabold uppercase tracking-wider ${
                          selectedRowForModal._severity === 'High' 
                            ? 'bg-rose-100 text-rose-700 dark:bg-rose-500/20 dark:text-rose-300 border border-rose-200 dark:border-rose-500/30' 
                            : 'bg-amber-100 text-amber-700 dark:bg-amber-500/20 dark:text-amber-300 border border-amber-200 dark:border-amber-500/30'
                        }`}>
                          {selectedRowForModal._severity || 'Detected'}
                        </span>
                      </div>
                      <p className="text-xs text-slate-500 dark:text-[#8ba3c9] mt-0.5 font-normal">
                        {activeTab === 'duplicates' 
                          ? `Comparing Flagged Row #${selectedRowForModal.id} with Matched Original Row #${selectedRowForModal._targetIndex ?? '?'}`
                          : `Diagnosing detected anomalies for Record #${selectedRowForModal.id}`}
                      </p>
                    </div>
                  </div>

                  {/* Close 'X' Button */}
                  <button
                    onClick={() => setSelectedRowForModal(null)}
                    className="p-2.5 rounded-xl text-slate-400 hover:text-slate-700 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-[#0e2755] transition-colors border border-transparent hover:border-slate-200 dark:hover:border-[#1a325a]"
                    title="Close comparison modal"
                  >
                    <X className="w-5 h-5" />
                  </button>
                </div>

                {/* Modal Body - Scrollable */}
                <div className="p-6 overflow-y-auto flex-1 space-y-6">
                  
                  {/* Top Insight Card */}
                  <div className={`p-4 rounded-2xl border flex items-start gap-3.5 ${
                    activeTab === 'duplicates'
                      ? 'bg-indigo-50/50 dark:bg-[#0a1e45]/50 border-indigo-100 dark:border-indigo-500/20 text-indigo-900 dark:text-indigo-200'
                      : 'bg-rose-50/50 dark:bg-[#2a0f1b]/50 border-rose-100 dark:border-rose-500/20 text-rose-900 dark:text-rose-200'
                  }`}>
                    <Info className="w-5 h-5 flex-shrink-0 mt-0.5 text-indigo-500 dark:text-indigo-400" />
                    <div className="text-xs space-y-1">
                      <p className="font-semibold text-sm">
                        {activeTab === 'duplicates'
                          ? `Detection Method: ${selectedRowForModal._method || 'Exact Match'} (Confidence: ${(Number(selectedRowForModal._confidence || 1) * 100).toFixed(1)}%)`
                          : `Identified by: ${(selectedRowForModal._methods || ['Anomaly Engine']).join(', ')}`}
                      </p>
                      <p className="opacity-90 leading-relaxed">
                        {selectedRowForModal._reason || 'This row has identical or highly similar attributes to another record in the dataset.'}
                      </p>
                    </div>
                  </div>

                  {/* For DUPLICATES: Complete Attribute-by-Attribute Comparison Table */}
                  {activeTab === 'duplicates' && (
                    <div className="space-y-4">
                      <div className="grid grid-cols-2 gap-4">
                        <div className="p-4 rounded-2xl bg-amber-50/60 dark:bg-[#1a253a] border border-amber-200/60 dark:border-amber-500/30">
                          <span className="text-[11px] font-bold uppercase tracking-wider text-amber-700 dark:text-amber-400">
                            Flagged Duplicate Record
                          </span>
                          <h4 className="text-lg font-bold text-slate-900 dark:text-white mt-0.5">
                            Row #{selectedRowForModal.id}
                          </h4>
                        </div>

                        <div className="p-4 rounded-2xl bg-blue-50/60 dark:bg-[#0c244d] border border-blue-200/60 dark:border-blue-500/30">
                          <span className="text-[11px] font-bold uppercase tracking-wider text-blue-700 dark:text-blue-400">
                            Matched Original Record
                          </span>
                          <h4 className="text-lg font-bold text-slate-900 dark:text-white mt-0.5">
                            Row #{selectedRowForModal._targetIndex ?? '?'}
                          </h4>
                        </div>
                      </div>

                      {/* Detailed Diff Table */}
                      <div className="rounded-2xl border border-slate-200 dark:border-[#1a325a] overflow-hidden">
                        <table className="w-full text-left text-xs">
                          <thead className="bg-slate-50 dark:bg-[#0a1e45] text-slate-600 dark:text-slate-300 uppercase font-bold border-b border-slate-200 dark:border-[#1a325a]">
                            <tr>
                              <th className="px-4 py-3 w-1/4">Column / Attribute</th>
                              <th className="px-4 py-3 w-1/3 bg-amber-50/40 dark:bg-amber-950/20 text-amber-900 dark:text-amber-300">
                                Duplicate Row (#{selectedRowForModal.id})
                              </th>
                              <th className="px-4 py-3 w-1/3 bg-blue-50/40 dark:bg-blue-950/20 text-blue-900 dark:text-blue-300">
                                Matched Original (#{selectedRowForModal._targetIndex ?? '?'})
                              </th>
                              <th className="px-4 py-3 text-right">Comparison</th>
                            </tr>
                          </thead>
                          <tbody className="divide-y divide-slate-100 dark:divide-[#1a325a]">
                            {dataset?.headers?.filter(h => h !== '__row_id').map((header) => {
                              const dupVal = String(selectedRowForModal[header] ?? '');
                              const origVal = selectedRowForModal._targetRow 
                                ? String(selectedRowForModal._targetRow[header] ?? '') 
                                : '';
                              
                              const isExact = dupVal.trim().toLowerCase() === origVal.trim().toLowerCase();
                              const isIdCol = header.toLowerCase() === 'id' || header.toLowerCase().endsWith('_id');

                              return (
                                <tr 
                                  key={header}
                                  className={!isExact && !isIdCol 
                                    ? 'bg-amber-50/70 dark:bg-amber-500/10' 
                                    : 'hover:bg-slate-50/50 dark:hover:bg-[#0a1f44]/40'}
                                >
                                  <td className="px-4 py-3 font-semibold text-slate-800 dark:text-slate-200">
                                    {header}
                                    {isIdCol && (
                                      <span className="ml-1.5 text-[10px] px-1.5 py-0.5 rounded bg-slate-200 dark:bg-slate-700 text-slate-600 dark:text-slate-300 font-normal">
                                        Key
                                      </span>
                                    )}
                                  </td>
                                  <td className={`px-4 py-3 font-mono ${
                                    !isExact && !isIdCol 
                                      ? 'font-bold text-amber-700 dark:text-amber-300' 
                                      : 'text-slate-700 dark:text-slate-300'
                                  }`}>
                                    {dupVal || <span className="text-slate-400 italic">null / empty</span>}
                                  </td>
                                  <td className={`px-4 py-3 font-mono ${
                                    !isExact && !isIdCol 
                                      ? 'font-bold text-blue-700 dark:text-blue-300' 
                                      : 'text-slate-700 dark:text-slate-300'
                                  }`}>
                                    {origVal || <span className="text-slate-400 italic">null / empty</span>}
                                  </td>
                                  <td className="px-4 py-3 text-right">
                                    {isIdCol ? (
                                      <span className="inline-flex items-center gap-1 text-[11px] font-medium text-slate-400">
                                        Unique Key
                                      </span>
                                    ) : isExact ? (
                                      <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-emerald-100 text-emerald-700 dark:bg-emerald-500/20 dark:text-emerald-300">
                                        <Check className="w-3 h-3" /> Identical
                                      </span>
                                    ) : (
                                      <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-amber-100 text-amber-700 dark:bg-amber-500/20 dark:text-amber-300">
                                        <AlertCircle className="w-3 h-3" /> Formatted / Diff
                                      </span>
                                    )}
                                  </td>
                                </tr>
                              );
                            })}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  )}

                  {/* For ANOMALIES: Diagnostic Outlier Evidence & Full Values Table */}
                  {activeTab === 'anomalies' && (
                    <div className="space-y-5">
                      {/* Detected Anomaly Cards */}
                      <div className="space-y-3">
                        <h4 className="text-sm font-bold text-slate-800 dark:text-white uppercase tracking-wider">
                          Detected Outliers & Rule Breaches
                        </h4>
                        {(selectedRowForModal._details || []).map((detail, dIdx) => (
                          <div 
                            key={dIdx} 
                            className="p-4 rounded-2xl border border-rose-200 dark:border-rose-500/30 bg-rose-50/40 dark:bg-rose-950/20 space-y-2 text-xs"
                          >
                            <div className="flex items-center justify-between">
                              <span className="font-bold text-rose-700 dark:text-rose-300 text-sm flex items-center gap-1.5">
                                <AlertTriangle className="w-4 h-4" />
                                {detail.column ? `Column: "${detail.column}"` : 'Multivariate Row Outlier'}
                              </span>
                              <span className="px-2 py-0.5 bg-rose-100 dark:bg-rose-500/20 text-rose-800 dark:text-rose-300 rounded font-mono font-bold">
                                {detail.method}
                              </span>
                            </div>
                            <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
                              {detail.reason}
                            </p>
                            {detail.recommendedAction && (
                              <p className="text-indigo-600 dark:text-indigo-400 font-medium">
                                ➔ <strong>Action:</strong> {detail.recommendedAction}
                              </p>
                            )}
                          </div>
                        ))}
                      </div>

                      {/* Complete Row Values Table */}
                      <div className="space-y-2">
                        <h4 className="text-sm font-bold text-slate-800 dark:text-white uppercase tracking-wider">
                          Complete Row Attribute Snapshot
                        </h4>
                        <div className="rounded-2xl border border-slate-200 dark:border-[#1a325a] overflow-hidden">
                          <table className="w-full text-left text-xs">
                            <thead className="bg-slate-50 dark:bg-[#0a1f44] text-slate-600 dark:text-slate-300 uppercase font-bold border-b border-slate-200 dark:border-[#1a325a]">
                              <tr>
                                <th className="px-4 py-2.5">Attribute</th>
                                <th className="px-4 py-2.5">Recorded Value</th>
                                <th className="px-4 py-2.5 text-right">Status</th>
                              </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-100 dark:divide-[#1a325a]">
                              {dataset?.headers?.filter(h => h !== '__row_id').map((header) => {
                                const val = String(selectedRowForModal[header] ?? '');
                                const isOutlier = (selectedRowForModal._headers || []).includes(header);

                                return (
                                  <tr 
                                    key={header}
                                    className={isOutlier 
                                      ? 'bg-rose-50/80 dark:bg-rose-500/15' 
                                      : 'hover:bg-slate-50/50 dark:hover:bg-[#0a1f44]/40'}
                                  >
                                    <td className="px-4 py-2.5 font-semibold text-slate-800 dark:text-slate-200">
                                      {header}
                                    </td>
                                    <td className={`px-4 py-2.5 font-mono ${
                                      isOutlier ? 'font-bold text-rose-600 dark:text-rose-400' : 'text-slate-700 dark:text-slate-300'
                                    }`}>
                                      {val || <span className="text-slate-400 italic">null / empty</span>}
                                    </td>
                                    <td className="px-4 py-2.5 text-right">
                                      {isOutlier ? (
                                        <span className="px-2 py-0.5 bg-rose-100 text-rose-700 dark:bg-rose-500/20 dark:text-rose-300 rounded-full font-bold text-[10px]">
                                          Outlier Flagged
                                        </span>
                                      ) : (
                                        <span className="text-slate-400 text-[11px]">Valid</span>
                                      )}
                                    </td>
                                  </tr>
                                );
                              })}
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                  )}

                </div>

                {/* Modal Footer */}
                <div className="p-4 px-6 border-t border-slate-100 dark:border-[#1a325a] bg-slate-50/70 dark:bg-[#05142e]/80 flex items-center justify-between">
                  <span className="text-xs text-slate-400">
                    Press <kbd className="px-1.5 py-0.5 bg-slate-200 dark:bg-slate-700 rounded text-[10px] font-mono">ESC</kbd> or click outside to dismiss
                  </span>
                  <button
                    onClick={() => setSelectedRowForModal(null)}
                    className="px-5 py-2 bg-slate-200 hover:bg-slate-300 dark:bg-[#1a325a] dark:hover:bg-[#234275] text-slate-800 dark:text-white rounded-xl text-xs font-bold transition-all"
                  >
                    Close Comparison
                  </button>
                </div>
              </div>
            </div>
          )}

        </div>
      )}
    </div>
  );
}
